---

  name: build and deliver cowsay app

  on:
    push:

  jobs:
    build:
      name: build go code into binary
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '>=1.23'

        - run: go version

        - run: |
            go mod init github.com/SLassalle/go-cowsay
            go mod tidy
            go run .
            go build -o bin/cowsay .