---

  name: build and deliver cowsay app

  on:
    push:

  env:
    REGISTRY: docker.io
    IMAGE_NAME: slassalle/go-cowsay

  jobs:
    build:
      name: build go code into binary
      strategy:
        matrix:
          arch:
            - amd64
            - arm64

      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-go@v5
          with:
            go-version: '>=1.23'

        - run: go version

        - run: |
            go mod init github.com/SLassalle/go-cowsay
            go mod tidy
            go build -o bin/cowsay .
          env:
            GOARCH: ${{ matrix.arch }}
        
        - run: |
            cp Dockerfile bin/

        - name: Upload static files as artifact
          id: deployment
          uses: actions/upload-artifact@v4
          with:
            path: bin/
            name: cowsaybin-${{ matrix.arch }}

    # deploy:
    #   name: deploy
    #   needs: build
    #   runs-on: ubuntu-latest
    #   steps:
    #     - uses: actions/download-artifact@v4
    #       with:
    #         path: .
    #         name: cowsaybin
    #     - run: |
    #         chmod u+x cowsay
    #         ./cowsay

    push-docker:
      name: push in dockerhub registry
      strategy:
        matrix:
          arch:
            - amd64
            - arm64
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with:
            path: .
            name: cowsaybin-${{ matrix.arch }}

        - run: |
            chmod u+x cowsay

        - run: |
            pwd
            ls -alh

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: |
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            tags: |
              latest-${{ matrix.arch }}

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            platforms: linux/${{ matrix.arch }}